## A review of numpy arrays and matrices + matplotlib
Open an interactive python environment (python shell, ipython shell, or jupyter notebook), and run the following commands and see the output. Do not close the environment

### Creating numpy arrays

In [1]:
import numpy as np
l = [1, 2, 3]
print(l)
a = np.array(l)
print(a)

print(f'type(l) : {type(l)}')
print(f'type(a) : {type(a)}')

[1, 2, 3]
[1 2 3]
type(l) : <class 'list'>
type(a) : <class 'numpy.ndarray'>


In [2]:
a = np.zeros(10)
print(a)
print(f'a.dtype : {a.dtype}')
a[2] = 4
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
a.dtype : float64
[0. 0. 4. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
a = np.zeros(10, dtype=np.int64)
print(a)
print(f'a.dtype : {a.dtype}')

[0 0 0 0 0 0 0 0 0 0]
a.dtype : int64


In [4]:
a = np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
a = np.full(5,123)
print(a)

[123 123 123 123 123]


In [6]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


### Numpy array basic properties and methods

In [7]:
a = np.array([1, 2, 3])
print(f'len(a) : {len(a)}')
print(f'a.shape : {a.shape}')
print(f'type(a) : {type(a)}')
print(f'a.size : {a.size}')
print(f'a.ndim : {a.ndim}')
print(f'a.dtype : {a.dtype}')

len(a) : 3
a.shape : (3,)
type(a) : <class 'numpy.ndarray'>
a.size : 3
a.ndim : 1
a.dtype : int32


### Lists vs numpy array

In [8]:
l1 = [1,2,3]
l2 = [4,5,6]

a1 = np.array(l1)
a2 = np.array(l2)

print(f'l1 + l2 : {l1 + l2}')
print(f'a1 + a2 : {a1 + a2}')

l1 + l2 : [1, 2, 3, 4, 5, 6]
a1 + a2 : [5 7 9]


### Basic operations

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(f'a+b : {a+b}')
print(f'a-b : {a-b}')
print(f'a*b : {a*b}')
print(f'b**a : {b**a}')
print(f'a+4 : {a+4}')
print(f'a*2 : {a*2}')
print(f'b/a : {b/a}')    # Note that the output type is float !
print(f'b//a : {b//a}')

a+b : [5 7 9]
a-b : [-3 -3 -3]
a*b : [ 4 10 18]
b**a : [  4  25 216]
a+4 : [5 6 7]
a*2 : [2 4 6]
b/a : [4.  2.5 2. ]
b//a : [4 2 2]


### Slicing

In [10]:
a = np.array([0,10,20,30,40, 50, 60, 70, 80, 90, 100])
print(f'a : {a}')
print(f'a[2] : {a[2]}')
print(f'a[2:8] : {a[2:8]}')
print(f'a[2:-1] : {a[2:-1]}')
print(f'a[2:] : {a[2:]}')
print(f'a[:8] : {a[:8]}')
print(f'a[2:8:2] : {a[2:8:2]}')
print(f'a[8:2:-1] : {a[8:2:-1]}')
print(f'a[::-1] : {a[::-1]}')
print(f'a[[1,3,3,4,5]] : {a[[1,3,3,4,5]]}')

a : [  0  10  20  30  40  50  60  70  80  90 100]
a[2] : 20
a[2:8] : [20 30 40 50 60 70]
a[2:-1] : [20 30 40 50 60 70 80 90]
a[2:] : [ 20  30  40  50  60  70  80  90 100]
a[:8] : [ 0 10 20 30 40 50 60 70]
a[2:8:2] : [20 40 60]
a[8:2:-1] : [80 70 60 50 40 30]
a[::-1] : [100  90  80  70  60  50  40  30  20  10   0]
a[[1,3,3,4,5]] : [10 30 30 40 50]


### 2D Arrays

In [11]:
A = np.zeros((4,6))
print(A)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [12]:
A = np.ones((4,6), dtype = np.int32)
print(A)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [13]:
A = np.full((4, 3), 50.0)
print(A)

[[50. 50. 50.]
 [50. 50. 50.]
 [50. 50. 50.]
 [50. 50. 50.]]


In [14]:
A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(A)
print()
print(f'A[1,2] : {A[1,2]}')
print(f'A[0,-1] : {A[0,-1]}')
print(f'A.shape : {A.shape}')
print(f'A.shape[0] : {A.shape[0]}')
print(f'A.shape[1] : {A.shape[1]}')
print(f'A.shape[::-1] : {A.shape[::-1]}')
print(f'A.size : {A.size}')
print(f'A.ndim : {A.ndim}')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

A[1,2] : 7
A[0,-1] : 4
A.shape : (3, 4)
A.shape[0] : 3
A.shape[1] : 4
A.shape[::-1] : (4, 3)
A.size : 12
A.ndim : 2


In [15]:
print(f'A[0, :] = {A[0, :]}')
print(f'A[0, :].shape = {A[0, :].shape}')
print(f'A[[0], :] = {A[[0], :]}')
print(f'A[[0], :].shape = {A[[0], :].shape}')
print(f'A[:,2] = {A[:,2]}')
print(f'A[:,2].shape = {A[:,2].shape}')
print(f'A[:,[2]] = \n{A[:,[2]]}')
print(f'A[:,[2]].shape = {A[:,[2]].shape}')


A[0, :] = [1 2 3 4]
A[0, :].shape = (4,)
A[[0], :] = [[1 2 3 4]]
A[[0], :].shape = (1, 4)
A[:,2] = [ 3  7 11]
A[:,2].shape = (3,)
A[:,[2]] = 
[[ 3]
 [ 7]
 [11]]
A[:,[2]].shape = (3, 1)


In [16]:
print(f'A[1:3] = \n{A[1:3]}')
print()
print(f'A[1:3, :] = \n{A[1:3, :]}')
print()
print(f'A[:,:3] = \n{A[:,:3]}')
print()
print(f'A[:,::2] = \n{A[:,::2]}')
print()
print(f'A[:,::-1] = \n{A[:,::-1]}')

A[1:3] = 
[[ 5  6  7  8]
 [ 9 10 11 12]]

A[1:3, :] = 
[[ 5  6  7  8]
 [ 9 10 11 12]]

A[:,:3] = 
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]

A[:,::2] = 
[[ 1  3]
 [ 5  7]
 [ 9 11]]

A[:,::-1] = 
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [17]:
r = np.array([0, 1, 0, 2, 2])
print(f'A = \n{A}')
print()
print(f'A[r,:] = \n{A[r,:]}')

A = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

A[r,:] = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]
 [ 9 10 11 12]]


In [18]:
print(f'A = \n{A}')
print()
A[:,0] = 1
print(f'A = \n{A}')
print()
A[:,0] = [20,30,40]
print(f'A = \n{A}')

A = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

A = 
[[ 1  2  3  4]
 [ 1  6  7  8]
 [ 1 10 11 12]]

A = 
[[20  2  3  4]
 [30  6  7  8]
 [40 10 11 12]]


In [19]:
print(f'A = \n{A}')
print()
print(f'A.T = \n{A.T}')

A = 
[[20  2  3  4]
 [30  6  7  8]
 [40 10 11 12]]

A.T = 
[[20 30 40]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [20]:
B = np.array([[1,1,1,1], [2,2,2,2], [3,3,3,3]])
print(f'A = \n{A}')
print()
print(f'B = \n{B}')
print()
print(f'A+B = \n{A+B}')
print()
print(f'A*B = \n{A*B}')
print()
print(f'A.dot(B.T) = \n{A.dot(B.T)}')
print()
print(f'A @ B.T = \n{A.dot(B.T)}')
print()
print(f'A.dot(B) = \n{A.dot(B)}')    # What is the Error about ? 

A = 
[[20  2  3  4]
 [30  6  7  8]
 [40 10 11 12]]

B = 
[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]

A+B = 
[[21  3  4  5]
 [32  8  9 10]
 [43 13 14 15]]

A*B = 
[[ 20   2   3   4]
 [ 60  12  14  16]
 [120  30  33  36]]

A.dot(B.T) = 
[[ 29  58  87]
 [ 51 102 153]
 [ 73 146 219]]

A @ B.T = 
[[ 29  58  87]
 [ 51 102 153]
 [ 73 146 219]]



ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [ ]:
print(np.random.random((2,3)))
print()
print(help(np.random.random))

In [ ]:
print(np.random.rand(2,3))
print()
print(help(np.random.rand))

In [ ]:
print(np.random.randn(2,3))
print()
print(help(np.random.randn))

### Numpy slices are references (not copies)

In [ ]:
A = A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = A[: ,1]
print(f'A = \n{A}')
print()
print(f'b = {b}')
print()
b[1] = 100
print(f'A = \n{A}')
print()
print(f'b = {b}')

In [ ]:
b = A[: ,0].copy()
print(f'b = {b}')
print()
b[1] = -200
print(f'A = \n{A}')
print()
print(f'b = {b}')

### Masks

In [ ]:
A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(f'A = \n{A}')
print()
print(f'A > 2 = \n{A <8}')
print()
mask = A < 8
print(f'A[mask] = \n{A[mask]}')
print()
A[mask] *=2
print(f'A = \n{A}')

### Operations on arrays

In [ ]:
A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(f'A = \n{A}')
print()
print(f'A.sum() = {A.sum()}')
print()
print(f'A.sum(axis=0) = {A.sum(axis=0)}')
print()
print(f'A.sum(axis=1) = {A.sum(axis=1)}')
print()
print(f'A.min() = {A.min()}')
print()
print(f'A.min(axis=0) = {A.min(axis=0)}')
print()
print(f'A.max(axis=0, keepdims=True) = {A.max(axis=0, keepdims=True)}')   # Pay attention to the shape of array!
print()
print(f'A.mean(axis=1) = {A.mean(axis=1)}')
print()
print(f'A.prod(axis=0) = {A.prod(axis=0)}')
print()

### Reshaping

In [ ]:
A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(f'A = \n{A}')
print()
print(f'A.reshape(4,3) = \n{A.reshape(4,3)}')
print()
print(f'A.reshape(2,6) = \n{A.reshape(2,6)}')
print()
print(f'A.reshape(4,-1) = \n{A.reshape(4,-1)}')
print()
print(f'A.reshape(4,-1) = \n{A.reshape(12,)}')
print()
print(f'A.ravel() = \n{A.ravel()}')
print()

### Broadcasting

In [ ]:
A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = np.array([1, 0, 2, -2])
print(f'A = \n{A}')
print()
print(f'b = {b}')
print()
print(f'A-b = \n{A-b}')
print()

In [ ]:
c = np.array([1,2,3])     # What is the error about ?
print(f'A-c = \n{A-c}')

In [ ]:
c.shape = (3, 1)
print(f'c = \n{c}')
print()
print(f'A-c = \n{A-c}')

### Ploting with Matplotlib

In [ ]:
import matplotlib.pyplot as plt
x = np.arange(0, 2 * np.pi, 0.1)
print(f'x = {x}')
y = np.cos(x)
print(f'y = {y}')
plt.plot(x,y)
plt.show()

In [ ]:
plt.plot(x, np.sin(x), label = 'sin')
plt.plot(x, np.cos(x), label = 'cos')
plt.title('example')
plt.legend()
plt.show()